package com.exfantasy.server.service;

import static org.springframework.data.mongodb.core.FindAndModifyOptions.options;
import static org.springframework.data.mongodb.core.query.Criteria.where;
import static org.springframework.data.mongodb.core.query.Query.query;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.mongodb.core.MongoOperations;
import org.springframework.data.mongodb.core.query.Update;
import org.springframework.stereotype.Service;

import com.exfantasy.server.entity.Counter;

/**
 * <pre>
 * 取得指定 collection 下一個序號
 * 
 * 參考: <a href="http://stackoverflow.com/questions/36448921/how-we-create-autogenerated-field-for-mongodb-using-springboot">Auto Increment</a>
 * </pre>
 * 
 * @author tommy.feng
 *
 */
@Service
public class CounterService {
	
	@Autowired
	private MongoOperations mongo;

	public void addInitialCounter(String collectionName) {
		Counter counter = new Counter(collectionName, 0L);
		mongo.save(counter);
	}
	
	public Long resetSequence(String collectionName) {
		Counter counter 
			= mongo.findAndModify(
					query(where("_id").is(collectionName)), 
					new Update().set("seq", 0), 
					options().returnNew(true), 
					Counter.class
			  );
		return counter.getSeq();
	}

	public Long getNextSequence(String collectionName) {
		boolean collectionExists = mongo.collectionExists(Counter.class);
		if (!collectionExists) {
			mongo.createCollection(Counter.class);
		}
		
		boolean exists = mongo.exists(query(where("_id").is(collectionName)), Counter.class);
		if (!exists) {
			addInitialCounter(collectionName);
		}
		
		Counter counter 
			= mongo.findAndModify(
					query(where("_id").is(collectionName)), 
					new Update().inc("seq", 1),
					options().returnNew(true), 
					Counter.class
			  );

		return counter.getSeq();
	}
}
